name: Build and Release APK

on:
  push:
    tags:
      - "v*" # Triggers only when a tag starting with "v" is pushed (e.g., v1.0.0)

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev automake libltdl-dev
          pip install --user --upgrade Cython virtualenv
          pip install --user --upgrade buildozer
          echo 'export PATH=$PATH:~/.local/bin/' >> ~/.bashrc
          source ~/.bashrc

      - name: Write GCP SA Key for App
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          mkdir -p ./assets
          echo "${{ secrets.GCP_SA_KEY }}" > ./assets/service_account.json

      - name: Build APK
        run: |
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          sudo update-java-alternatives --set ${JAVA_HOME}
          export PATH=$JAVA_HOME/bin:$PATH

          # Clean Buildozer and Python-for-Android caches
          buildozer android clean || true
          rm -rf .buildozer
          rm -rf bin
          rm -rf ~/.local/share/python-for-android

          # Build the APK
          yes | buildozer -v android debug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for version ${{ github.ref_name }}"
          draft: false
          prerelease: true
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
